### PR TITLE
Several updates to deployThroughARM.ps1

### PR DESCRIPTION
**Pull request by pcgeek86**
1. Updated string literals to use single quotes as best practice, to avoid accidental interpolation.
2. Removed unnecessary quotes around HashTable keys.
3. Added more relevant names to Resource Group and Automation Account names.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### CODE REVIEW

**Comment by JAL9302** [comment]
Hey @elcooper, in the future can you check with the owner before merging? This all looks fine except I don't like the new names of the resource group and automation account that are created. More than just AA DSC resources are created -- this is meant to be a sample environment for all Azure Automation features.

Trevor can you do another pull request where they're named "SampleAutomationAccount" and "SampleAutomationResourceGroup" or similar?

**Comment by elcooper** [comment]
Sure thing.  Sorry about that Joe!

**Comment by pcgeek86** [comment]
@jodoglevy Joe, I just went to update this, but it look like you already have done so yesterday.

https://github.com/azureautomation/automation-packs/commit/3d358e1eb038ea9a293ed39b37d3c2f97fa96c33#diff-f1bbc499447edc8b9c3620ba2a1d404e

/cc @elcooper 

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by JAL9302** [comment]
Yup sorry forgot to update this thread

**Pull request merged**
